replicaCount: 1

image:
  repository: snk0202/kubeburner-controller
  tag: d8e2245
  pullPolicy: IfNotPresent

serviceAccount:
  name: kubeburner-controller-sa

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

env:
  - name: KB_CLIENT
    value: "client-1"
  - name: API_KEY
    value: "KBR_389hjhfhjHET56BDhfnfehj3nfnjd"
  - name: CLUSTER_NAME
    value: "dev-stage-cluster"