apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeburner-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: kubeburner-controller
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: kubeburner-controller
  template:
    metadata:
      labels:
        app: kubeburner-controller
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
      - name: kubeburner-controller
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 3000
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
